In [29]:
import numpy as np

In [30]:
# creating array in numpy
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [31]:
# basic array operation

a = np.array([[1,2],
             [4,5]])

b = np.array([[9,8],
             [6,5]])
print("Adding 1 to every element of array 'a' ",a+1)
print("Subtracting 1 to each element of array 'b' ",b-1)
print("Sum of all array elements ",a.sum())
print("Sum of both array 'a' and 'b' ",a+b)


Adding 1 to every element of array 'a'  [[2 3]
 [5 6]]
Subtracting 1 to each element of array 'b'  [[8 7]
 [5 4]]
Sum of all array elements  12
Sum of both array 'a' and 'b'  [[10 10]
 [10 10]]


In [32]:
# data type in numpy
x = np.array([1, 2])  
print(x.dtype)         
 
x = np.array([1.0, 2.0]) 
print(x.dtype)


int64
float64


In [33]:
# Maths operation in numpy
arr1 = np.array([[4, 7], [2, 6]], dtype=np.float64)
arr2 = np.array([[3, 6], [2, 8]], dtype=np.float64)

print(np.add(arr1, arr2))
print(np.sum(arr1))
print(np.sqrt(arr1))
print(arr1.T) # it transpose the array

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [34]:
# array generation function
#           (start,stop,jump)
arr1 = np.arange(1,11,2)
print(arr1)

# it fill the zeros to the array
arr2 = np.zeros(6)
print(arr2)

arr3 = np.zeros((3,3)) # 2d matrix 
print(arr3)

# it fill the ones to the array
arr4 = np.ones((2,2))
print(arr4)

# linspace :- gives equal space b/w element
#          (start,stop,totalElement)
arr5 = np.linspace(1,5,3)
print(arr5)

arr6 = np.linspace(1,5,8)
print(arr6)

[1 3 5 7 9]
[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[1. 3. 5.]
[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]
