In [5]:
import numpy as np

In [6]:
# creating array in numpy
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
# basic array operation

a = np.array([[1,2],
             [4,5]])

b = np.array([[9,8],
             [6,5]])
print("Adding 1 to every element of array 'a' ",a+1)
print("Subtracting 1 to each element of array 'b' ",b-1)
print("Sum of all array elements ",a.sum())
print("Sum of both array 'a' and 'b' ",a+b)


Adding 1 to every element of array 'a'  [[2 3]
 [5 6]]
Subtracting 1 to each element of array 'b'  [[8 7]
 [5 4]]
Sum of all array elements  12
Sum of both array 'a' and 'b'  [[10 10]
 [10 10]]


In [14]:
# data type in numpy
x = np.array([1, 2])  
print(x.dtype)         
 
x = np.array([1.0, 2.0]) 
print(x.dtype)


int64
float64


In [ ]:
# Maths operation in numpy
arr1 = np.array([[4, 7], [2, 6]], dtype=np.float64)
arr2 = np.array([[3, 6], [2, 8]], dtype=np.float64)

print(np.add(arr1, arr2))
print(np.sum(arr1))
print(np.sqrt(arr1))
print(arr1.T) # it transpose the array

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]
