In [1]:
import numpy as np

In [9]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
# indexing :- accessing the specific element
print(arr[2]) # 12
print(arr[4])

12
14


In [ ]:
# slicing :- extracting a portion of an array instead of just one element
arr = np.arange(10,25)
print(arr)

# slicing :- [start : stop : step]
print(arr[1:4])
print(arr[:3])
print(arr[5:])

# negative indexing
print(arr[-1:-6:-1])

# reverse
print(arr[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[11 12 13]
[10 11 12]
[15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [36]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

print("-------------------")

print(arr[0])

print("-------------------")
# Syntax :- [row,col]
print(arr[5,4]) # target 30 

print("-------------------")
# for printing
# 2  3
# 7  8
#        [row,col]
print(arr[0:2,1:3])
print("-------------------")

print(arr[3:,2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
-------------------
[1 2 3 4 5]
-------------------
30
-------------------
[[2 3]
 [7 8]]
-------------------
[[18 19 20]
 [23 24 25]
 [28 29 30]]
