In [3]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# Arithimetic operation
# arr1 and arr2 element must be equal
sum = arr1 + arr2
print(sum)

prod = arr1 * arr2
print(prod)

diff = arr2 - arr1
print(diff)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[5 5 5 5 5]


In [ ]:
# brodcasting
l = [1,2,3,4,5]
arr1 = np.array(l)
arr1 + 10
print(arr1)

# example 2
arr2 = np.arange(1,26).reshape(5,5)
arr2 + 5

[1 2 3 4 5]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# matrix operation
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[5,6], [7,8]])

# matrix addition
mat1 + mat2

array([[ 6,  8],
       [10, 12]])