In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# Arithimetic operation
# arr1 and arr2 element must be equal
sum = arr1 + arr2
print(sum)

prod = arr1 * arr2
print(prod)

diff = arr2 - arr1
print(diff)

div = arr1 / arr2
print(div)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[5 5 5 5 5]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [4]:
# brodcasting
l = [1,2,3,4,5]
arr1 = np.array(l)
arr1 + 10
print(arr1)

# example 2
arr2 = np.arange(1,26).reshape(5,5)
arr2 + 5

[1 2 3 4 5]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
# matrix operation
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[5,6], [7,8]])

# matrix addition
mat1 + mat2


array([[ 6,  8],
       [10, 12]])

In [6]:
# matrix multiplication :- use @ in between the matrix name
mat1 @ mat2

# one more way to matrix multiplication
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [7]:
# Transpose of matrix
mat1 = np.array([[1,2], [3,4]])
mat1.T

array([[1, 3],
       [2, 4]])

In [8]:
# Stacking Array
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


In [9]:
# vertically stacking
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# Horizontaly stacking
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# column stack arrange
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [12]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [14]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]