In [82]:
import numpy as np


In [83]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [84]:
# to know the sum of all the element present in s 
s.sum()

np.int64(405)

In [85]:
# to know the sum of each row 
row_sum = np.sum(s,axis=1)
print(row_sum)

# to check the sudoko is valid for rows
for i in row_sum:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
        print("Sudoko is valid")


[45 45 45 45 45 45 45 45 45]
Sudoko is valid


In [86]:
# to know the sum of each column
col_sum = np.sum(s,axis = 0)
print(col_sum)

# to check the sudoko is valid for columns
for i in col_sum:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("Sudoko is valid")

[45 45 45 45 45 45 45 45 45]
Sudoko is valid


In [87]:
# for checking each block has correct sudoko like 3X3 
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

    

45
45
45
45
45
45
45
45
45


In [88]:
# columns = Age , Maths marks , science marks

data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

# find the averag age of students
np.mean(data[:,0])


np.float64(18.4)

In [89]:
# extract maths marks of all students
print(data[:,1])

[85 92 76 65 90]


In [90]:
# find the highest science marks
np.max(data[:,2])

np.int64(95)

In [91]:
# get details of the students who scored more than 90 in maths
data[data[:,1] > 90]

array([[19, 92, 88]])

In [92]:
# increase maths marks by 5 to all the students
data[:,1] += 5 # broadcasting method
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [93]:
# find how many student younger than 19
len(data[data[:,0] < 19])

3

In [94]:
# calculate the average marks of each subject
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [95]:
# get data of students who scored at least 80 in both subject
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [96]:
# replace all science marks less than 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])