In [1]:
import numpy as np

In [5]:
arr = np.arange(5,26,5)
print(arr)

[ 5 10 15 20 25]


In [7]:
# Create an array from 1 to 12 and reshape it into a 3 × 4 matrix.
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr3 = np.array([5, 10, 15, 20, 25])
# print the first element using indexing
print(arr3[0])

# Third element
print(arr3[2])

#Last element (using negative indexing)
print(arr3[-1]) 

5
15
25


In [16]:
# mathematical operation 
# add 5 to every element
arr4 = np.array([2,4,6,8])
sum = arr4 + 5
sum

array([ 7,  9, 11, 13])

In [17]:
# multiply every element by 3
mul = arr4 * 3
mul

array([ 6, 12, 18, 24])

In [18]:
# using broadcasting add b to a
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
# stacking
x = np.array([1,2,3])

y = np.array([4,5,6])

print(np.hstack((x,y)))


[1 2 3 4 5 6]


In [24]:
print(np.vstack((x,y)))

[[1 2 3]
 [4 5 6]]


In [29]:
np.column_stack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
# Print only the even numbers using Boolean Indexing.
arr5 = np.arange(1,21)
bool_index = arr5 % 2 == 0
print(bool_index)

arr5 = arr5[bool_index]
print(arr5)

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]
[ 2  4  6  8 10 12 14 16 18 20]
