In [2]:
import numpy as np

In [3]:
# create an array containing numbers from 1 to 30.
arr = np.arange(1,31)

# All even numbers using boolean indexing
even_num = arr % 2 == 0
print(even_num)
even = arr[even_num]
print(even)

print("-------------------------------------------------------------------------")
# All odd number 
odd_num = arr % 2 != 0
print(odd_num)
odd = arr[odd_num]
print(odd)

print("-------------------------------------------------------------------------")
# All odd number greater than 20
print(arr[(arr%2!=0) & (arr > 20) ])

print("-------------------------------------------------------------------------")
# All even number greatert than 20
print(arr[(arr%2==0) & (arr > 20)])

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
-------------------------------------------------------------------------
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
-------------------------------------------------------------------------
[21 23 25 27 29]
-------------------------------------------------------------------------
[22 24 26 28 30]


In [4]:
# Replace values

arr1 = np.array([5, 10, 15, 20, 25, 30, 35, 40])

 # Replace every number divisible by 10 with 100.
arr1[arr1 % 10 == 0] = 100
print(arr1)

print("------------------------------------")
# Replace all the number greater than 25 by 0
arr1[arr1 > 25] = 0
print(arr1)

[  5 100  15 100  25 100  35 100]
------------------------------------
[ 5  0 15  0 25  0  0  0]


In [5]:
# creating a matrix
mat  = np.array([[12, 25, 18],
 [45, 30, 60],
 [22, 15, 90]])

# Maximum of each row
row_max = np.max(mat,axis=1)
print("Maximum of each row : ",row_max)

# Maximum of each column
col_max = np.max(mat,axis=0)
print("Maximum of each col : ",col_max)

# Sum of each row
sum_row = np.sum(mat,axis=1)
print("Sum of each row : ",sum_row)

# sum of wach column
sum_col = np.sum(mat,axis=0)
print("Sum of each column : ",sum_col)

# overall mean
overall_mean = np.mean(mat)
print("Over all mean : ",overall_mean)

Maximum of each row :  [25 60 90]
Maximum of each col :  [45 30 90]
Sum of each row :  [ 55 135 127]
Sum of each column :  [ 79  70 168]
Over all mean :  35.22222222222222


In [6]:
# reshaping challenge
arr2 = np.arange(1,37).reshape(6,6)
print(arr2)

print(arr2.reshape(6, 6))
print(arr2.reshape(9, 4))
print(arr2.reshape(3, 12))
print(arr2.reshape(2, 18))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]]


In [7]:
# slicing challenges
arr3 = np.arange(1, 26).reshape(5,5)
print(arr3)
# first row
print(arr3[0,])

# Last column
print(arr3[0:,4])

# first column
print(arr3[0:,0])

# middle row
print(arr3[2])

# middle column
print(arr3[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[ 1  6 11 16 21]
[11 12 13 14 15]
[ 3  8 13 18 23]


In [8]:
# random operations
arr4 = np.random.randint(10, 100, (4, 4))

print("Original Matrix:")
print(arr4)


# Maximum value
print("\nMaximum Value:")
print(np.max(arr4))

# Minumum value
print("\nMinimum Value:")
print(np.min(arr4))

# Mean
print("\nMean:")
print(np.mean(arr4))

# Flatten and sort
print("\nSorted Flattened Array:")
print(np.sort(arr, axis=None))

Original Matrix:
[[11 75 82 11]
 [90 34 40 23]
 [80 86 45 23]
 [23 81 39 12]]

Maximum Value:
90

Minimum Value:
11

Mean:
47.1875

Sorted Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [9]:
# find the unique value
arr5 = np.array([2,4,2,5,7,5,2,8,4,9,8,8])
# np.unique() removes duplicates and returns only distinct values in sorted order.
print(np.unique(arr5))

# To count how many times each unique value appears, use:
unique, count = np.unique(arr5, return_counts=True)
print(unique)
print(count)

[2 4 5 7 8 9]
[2 4 5 7 8 9]
[3 2 2 1 3 1]


In [10]:
arr6 = np.arange(1,31)
print(arr6)

# Replace all multiples of 3 with -1
arr6[arr6 % 3 == 0] = -1
arr6

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


array([ 1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1, 16, 17,
       -1, 19, 20, -1, 22, 23, -1, 25, 26, -1, 28, 29, -1])

In [11]:
# matrix multiplication
X = np.array([
    [1, 2],
    [3, 4]
])

W = np.array([
    [5, 6],
    [7, 8]
])

result = X @ W
print(result)

[[19 22]
 [43 50]]
